name: cron-schedule

on:
  schedule:
    - cron: '30 3,6,12,18 * * *'

  workflow_dispatch:

jobs:
  schedule_run:
    runs-on: ubuntu-22.04
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DATABASE_ID: ${{ secrets.DATABASE_ID }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: site
          submodules: recursive
          fetch-depth: 0
      
      - name: Install Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Run Script
        run: |
          python3 ./tools/script.py
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "cron auto commit"
          branch: site
